version: '3.4'

services:
  myprofilevuejs:
    image: myprofilevuejs
    network_mode: bridge
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090:8090
    volumes:
      - "var/run/docker.sock:/var/run/docker.sock"

